SYSENG-8438: Adding option for glob patterns and exclude paths
life360/buildpipe-buildkite-plugin pull request #2
Opened 2022-01-25 19:26 UTC by cacmartinez

Description:

- Adds `exclude_path` option to the project yml definition to be able to ignore certain paths that could match a previously defined matching path.
- Adds possibility to use glob patterns in both `path` and `exclude_path` options.

Addresses:
https://life360.atlassian.net/browse/SYSENG-8438

2022-01-26 08:09 UTC, mgarza-life360 requested changes
This is awesome, going to be so helpful. You mentioned testing against your own fork, have you also tested in Buildkite itself? I think we should do some testing on a branch and really try to break a project with very fine tuned paths and exclude paths. 

Would also help us compare the performance of the changes when there are a decent number of changed files.

2022-01-26 08:09 UTC, mgarza-life360 commented on project.go
> +func matchPath(p string, f string) (bool, error) {
Suggestion: The error return value is not being consumed, I would update this to only return a `bool`. And within the error check, log the error instead `log.Debugf("path matching failed: %v", err)`. If the error isn't descriptive enough, could even format it to include the file and path strings that caused the error.

2022-01-26 08:09 UTC, mgarza-life360 commented on project.go
> +	CHANGED_FILES_LOOP:
Required: A bug in this logic can prevent required CI checks from running, please add some additional checks using excluded paths in the `TestCheckAffected` test function within `project_test.go`.

2022-01-26 08:09 UTC, mgarza-life360 commented on project.go
> +	"fmt"
Suggested: If the error logging comment below is implemented, `fmt` can be removed.

2022-01-26 17:36 UTC, cacmartinez commented on README.md
> +     - project4/scripts/**/*.swift
yeah that is the correct assumption. 

The process is: 
1. Check on every changed file go one by one in the paths and see if it matches, if it finds one that matches it then checks the excluded paths and checks that it doesn't match one. 
1a. If nothing matches in the excluded paths then it means the project has changes
1b. If something does match in the excluded paths then the file is not a match for the project and therefore continues with the next file.

2022-01-26 17:55 UTC, cacmartinez commented on project.go
> +				}
Yeah that triple nested loop is not ideal. I don't think removing all of the files from excluded paths would be more optimal, because that would mean that for each modified file I would have to check if they are excluded. Right now I am only checking for excluded if they actually matched one of the paths in the project and early returning as soon as possible which cuts many unnecessary checks for excluded paths.

Also one advantage is that the `paths` and `excluded_paths` will generally be a really small number which could basically be considered some constant. I don't think we will ever have more that 10 paths or excluded paths.

I tried thinking of way of optimize it but given that the paths and excluded files match multiple files, it wouldn't be that straight forward. And given the small size that `paths` and `excluded_paths` the benefit might not be that much. Besides weren't we now removing the pods installed from the projects as something to be ignored now that they can be downloaded fast?

2022-01-26 17:59 UTC, cacmartinez commented on project.go
> +	CHANGED_FILES_LOOP:
Sure will add it, haven't worked with tests before in go but will take a look at how they work.

2022-01-26 19:51 UTC, mgarza-life360 commented on project.go
> +				}
`doublestar.Match` has nesting itself as well: https://github.com/bmatcuk/doublestar/blob/master/match.go

While the `paths` and `excluded_paths` lists themselves will be small, the recursive nature of the wildcards can make the size of the searching within a single path entry quite large, that is one of the variable values. Thinking of something like `Pods/**`.

We iterate through every file in `changedFiles` (for every project also), check if the file is included in the the project's paths, and then have to check against every excluded path. But if we could get a subset of `changedFiles` that already has paths that would be excluded removed, we only have to check for matched included paths again.

The best and worst case are just so far apart here. Best case, the first changed file matches the project included paths and is not part of excluded paths, `true` is returned and this breaks out early for this project. Worst case, the last changed file matches the project included path.

I think we just need to throw some branches up in the mono repo and test a few cases. If PRs with hundreds of file changes and PRs with a few file changes perform the same, then we have nothing to worry about and are just trying to optimize a problem that doesn't exist yet.

2022-01-26 19:54 UTC, mgarza-life360 commented on README.md
> +     - project4/scripts/**/*.swift
Cool, makes sense with the wildcards.

2022-01-26 21:40 UTC, cacmartinez commented on project.go
> +				}
Yeah using glob patterns makes it heavier, so it is better to avoid them if possible. They should only be used when necessary. For example in pods it would be better to use exclude with `Pods/` rather than `Pods/**` (without using any `*`). That way the comparison doesn't go into `doublestar` and becomes a simple string comparison to see if the modified file starts with the path pattern. Unfortunately optimizing that `doublestar` would be complex and not worth the effort if we can reduce its usage for most cases.

As for iterating through each project that would unfortunately be necessary because each project defines its own paths and their own exclusions. We wouldn't be able to discard based on things found already in other project.

I will implement the proposed solution, because after thinking about it again I think you are right it might be much more common the worst case scenario: when things match the pattern and don't match any of the excluded paths in which case doing the filtering first would be O(np + ne) vs O(npe).

2022-01-27 02:35 UTC, cacmartinez commented on project.go
> +				}
implemented the change now

2022-01-27 03:58 UTC, mgarza-life360 commented on project.go
> +				}
Nice, hopefully this helps a bit!

2022-01-27 04:12 UTC, mgarza-life360 commented on project.go
> +	CHANGED_FILES_LOOP:
Cool, a lot of good test changed files! Did you get them running okay? I don't remember exactly which guide I followed, but it was basically getting docker setup and hooked up with VSCode, and the tests would run via that.

2022-01-27 04:14 UTC, mgarza-life360 approved these changes
Everything LGTM. 

How did you want to do the integration testing? We'll create a test branch(es) in the mono repo with various levels of changes and have special steps in BK that only run on those branches. But did you want to test off your branch first or tag a version and test off that?

2022-01-27 16:20 UTC, cacmartinez commented
> Everything LGTM.
> 
> How did you want to do the integration testing? We'll create a test branch(es) in the mono repo with various levels of changes and have special steps in BK that only run on those branches. But did you want to test off your branch first or tag a version and test off that?

@mgarza-life360 I think I will need to create a tag and based off that. I didn't find how to use a plugin based off a branch. Also the hook code was changed to directly download binaries so even if I could run plugin from a branch it wouldn't work unless I create a release. I did tested on my personal fork first though, so if there is an error it would be because I messed something when porting the code to the life360 fork.

2022-01-27 16:21 UTC, merged