Users/dbrovkin/main/syseng 15571 expose pipeline env
life360/buildpipe-buildkite-plugin pull request #7
Opened 2022-11-03 07:02 UTC by dbrovkin360

This PR improves .yml generation, and exposes pipeline level ENV variable. 

Example of output yml pipeline format:

`env: 
  BUNDLE_JOBS: '4', 
  BUNDLE_RETRY: '3', 
  LANG: en_US.UTF-8, 
  LC_ALL: en_US.UTF-8,
  SDK_RELATIVE_PATH: 'true', 
  XCODE: 13.4.1
  
steps:
- artifact_paths: [build_output/**/*, build_logs/**/*]
  command: scripts/buildkite/build_unit_tests.sh
  env: {BUILDPIPE_PROJECT_LABEL: AwarenessEngine, BUILDPIPE_PROJECT_PATH: AwarenessEngine/,
    BUILDPIPE_SCOPE: project, BUNDLE_JOBS: '4', BUNDLE_RETRY: '3', LANG: en_US.UTF-8,
    LC_ALL: en_US.UTF-8, SDK_RELATIVE_PATH: 'true', XCODE: 13.4.1}
  key: build-unit-tests:AwarenessEngine
  label: ':fastlane: Build Unit Tests - AwarenessEngine'
  notify:
  - github_commit_status: {context: buildkite/awarenessengine-unit-tests-build}
  plugins:

.......`

After pipeline Env vars are properly exposed, ${XCODE} works well for the plugins step. 
<img width="2056" alt="Screen Shot 2022-11-03 at 2 55 54 AM" src="https://user-images.githubusercontent.com/115962608/199663459-6c1f7c31-f7dd-489d-bd78-968905b02ed3.png">

2022-11-03 20:48 UTC, mgarza-life360 requested changes
The `yaml` outputted doesn't pass a yaml lint.

This is something we want to test end-to-end before merging. You can update the https://buildkite.com/life360-inc/systems-sdk-pull-requests steps to have a custom unit test pipeline upload use this branch for Buildpipe. I can help you set this up.

2022-11-03 20:48 UTC, mgarza-life360 commented on pipeline.go
> +	Env map[string]string `yaml:"env"`
We probably don't want to add anything new to the pipeline, only tweak what we need. The env vars are already passed from the pipeline to the step with Buildpipe, can look at one of your uploaded steps as an example

```
Pipeline:

steps:

- artifact_paths:

  - build_output/**/*

  - build_logs/**/*

  command: scripts/buildkite/build_unit_tests.sh

  env:

    BUILDPIPE_PROJECT_LABEL: AwarenessEngine

    BUILDPIPE_PROJECT_PATH: AwarenessEngine/

    BUILDPIPE_SCOPE: project

    BUNDLE_JOBS: "4"

    BUNDLE_RETRY: "3"

    LANG: en_US.UTF-8

    LC_ALL: en_US.UTF-8

    SDK_RELATIVE_PATH: "true"

    XCODE: 13.4.1

  key: build-unit-tests:AwarenessEngine

  label: ':fastlane: Build Unit Tests - AwarenessEngine'

  notify:

  - github_commit_status:

      context: buildkite/awarenessengine-unit-tests-build

  plugins:

  - ssh://git@github.com/life360/cache-buildkite-plugin.git#skip_restore_upload:

      backend: s3

      compress: true

      id: awarenessengine-unit-test-derived-data

      key: v1-cache-{{ id }}-{{ runner.os }}-xcode-$${XCODE}-{{ git.commit }}

      paths:

      - build_derived_data/Build/Products/*

      restore-keys:

      - v1-cache-{{ id }}-{{ runner.os }}-xcode-$${XCODE}-{{ git.commit }}

      s3:

        bucket: life360-devops-prod-01-buildkite-tmp-build-artifacts

      skip-restore: true

  - gencer/cache#v2.4.8:

      backend: s3

      compress: true

      id: ruby-ios-monorepo

      key: v1-cache-{{ id }}-{{ runner.os }}-{{ checksum 'Gemfile.lock' }}

      paths:

      - vendor/bundle

      restore-keys:

      - v1-cache-{{ id }}-{{ runner.os }}-

      - v1-cache-{{ id }}-

      s3:

        bucket: life360-devops-prod-01-buildkite-tmp-build-artifacts

  - ssh://git@github.com/life360/repo-shallow-clone-buildkite-plugin.git#0.1.3:

      depth: 1

      run_on_pull_requests: true

  - ssh://git@github.com/life360/aws-sm-buildkite-plugin.git#json-to-file:

      assume-role-arn: arn:aws:iam::778631518827:role/buildkite_ios_role

      json-to-env:

      - secret-id: arn:aws:secretsmanager:us-east-1:778631518827:secret:devops/mobile/iphone-github-pat

      region: us-east-1

  timeout_in_minutes: 20
```

2022-11-03 20:48 UTC, mgarza-life360 commented on go.mod
> +	golang.org/x/sys v0.1.0 // indirect
What is this for? I'm not sure what you are trying to import as I don't see any usage anywhere.

Since this looks like a standard go library, could you not import it at the top of `pipeline.go`?

2022-11-04 14:46 UTC, dbrovkin360 commented on pipeline.go
> +	Env map[string]string `yaml:"env"`
so, I did various testings, and env variables declared at `step` level are accessible within `command: ... ` scope only. For some reasons these vars won't be visible at `plugin ` stage. 
The change I've made is simply moving all pipeline level env vars, from the **original yml** file to the **new generated yml file**. Same logic works today in the iPhone repo UT pipeline.

2022-11-04 14:49 UTC, dbrovkin360 commented on go.mod
> +	golang.org/x/sys v0.1.0 // indirect
I was not able to export go exec binary (`go build`), and searched for the solution. I found this fix that helped:
`go get -u golang.org/x/sys`
After running this command, `go build` worked like a charm. Please check on your end to build executable, and if it works without my change - I will remove it. Thanks

2022-11-07 19:31 UTC, dbrovkin360 commented
@mgarza-life360 I ran UTs, and they all passed. I also run "Checks projects affected" test using local docker. 
<img width="583" alt="Screen Shot 2022-11-07 at 11 31 30 AM" src="https://user-images.githubusercontent.com/115962608/200398067-772fd750-f916-40d0-b83b-387096f7f7ad.png">
<img width="774" alt="Screen Shot 2022-11-07 at 2 31 49 PM" src="https://user-images.githubusercontent.com/115962608/200398151-60d48bcd-7cf0-4965-9cc4-d804b73869d4.png">

2022-11-09 01:58 UTC, mgarza-life360 approved these changes
🚀

2022-11-09 01:59 UTC, merged